### ISSUE TITLE
 Error: The following plugins are required, but not installed

### ISSUE THREAD

**Issue by kaiyuanlim-adh** [toowoxx/terraform-provider-packer#18] opened 2024-07-16 09:23 UTC
**Describe the bug**
I got an error when running terraform apply.

```
2024-07-16T07:06:21.4589401Z [33m│[0m [0mOutput: Error: Missing plugins
2024-07-16T07:06:21.4589615Z [33m│[0m [0m
2024-07-16T07:06:21.4589871Z [33m│[0m [0mThe following plugins are required, but not installed:
2024-07-16T07:06:21.4590104Z [33m│[0m [0m
2024-07-16T07:06:21.4590338Z [33m│[0m [0m* github.com/hashicorp/azure ~> 1
2024-07-16T07:06:21.4590554Z [33m│[0m [0m
2024-07-16T07:06:21.4590800Z [33m│[0m [0mDid you run packer init for this project ?
2024-07-16T07:06:21.4591020Z [33m│[0m [0m
2024-07-16T07:06:21.4591208Z [33m│[0m [0m
2024-07-16T07:06:21.4591393Z [33m│[0m [0m
2024-07-16T07:06:21.4591595Z [33m│[0m [0mError: exit status 1
```

**To Reproduce**

Using packer.pkr.hcl with content
```
packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 1"
    }
  }
}
```

**Expected behavior**
Terraform packer should run packer init before packer build

**Additional information (please complete the following information):**
 - Ubuntu 20.04
 - Terraform version: 1.5.4
 - Packer Provider version: 0.15.1

**Additional context**
* I currently have to include the binaries manually into my git repo to make this work.

**Comment by simaotwx** [comment] 2024-07-16 11:11
Thanks for reporting.
The provider does run packer init here: https://github.com/toowoxx/terraform-provider-packer/blob/main/provider/resource_packer_image.go#L219

I'll have to take a closer look at this.

**Comment by kaiyuanlim-adh** [comment] 2024-07-16 11:36
Okay, that is strange.

This might help.

```
resource "packer_image" "azdo" {
  directory = "${path.module}/packer"

  variables = {
    rg_name       = data.azurerm_resource_group.azdo.name
    rg_region     = data.azurerm_resource_group.azdo.location
    vm_size       = local.vm_size
    gallery_name  = azurerm_shared_image.azdo_ubuntu_22_04.gallery_name
    image_name    = azurerm_shared_image.azdo_ubuntu_22_04.name
    image_version = var.image_version
    disk_size     = local.disk_size
    azdo_username = local.azdo_username
    vnet_name     = local.name
  }

  triggers = {
    folder_hash = sha1(join("", [for f in fileset("packer", "*") : filesha1("${path.module}/packer/${f}")]))
  }
}

#And inside my "packer" folder

ls
agent.pkr.hcl		config			github.com		packer.pkr.hcl		scripts			variables.pkr.hcl
´´´

**Comment by kaiyuanlim-adh** [comment] 2024-07-29 06:05
Any updates?

**Comment by simaotwx** [comment] 2024-07-29 06:13
Not sure what the issue is, I will have to investigate further.
One thing I noticed Is that you can use this data source for your folder trigger: https://registry.terraform.io/providers/toowoxx/packer/latest/docs/data-sources/files

**Comment by kaiyuanlim-adh** [comment] 2024-07-29 07:13
> Not sure what the issue is, I will have to investigate further. One thing I noticed Is that you can use this data source for your folder trigger: https://registry.terraform.io/providers/toowoxx/packer/latest/docs/data-sources/files

Yes but i am already using "directory" in "packer_image" and i added a trigger.

The issue is that it does not seems to download and install the required plugins when i ran terraform apply.

**Comment by simaotwx** [comment] 2024-08-14 07:42
I'm unable to reproduce this at the HEAD of the branch. When the new version is released, please test again and let me know.

**Comment by kaiyuanlim-adh** [comment] 2024-08-14 07:51
And when will that be?
Thank you in advanced.

**Comment by simaotwx** [comment] 2024-08-14 07:54
> And when will that be?

I'll try to get it out today.

**Comment by simaotwx** [comment] 2024-08-19 09:56
I'm going to close this issue because I can't reproduce it on the latest version. If the issue persists please let me know.

**Closed as completed by simaotwx** 2024-08-19 09:56 UTC
Labels: bug

**Comment by kaiyuanlim-adh** [comment] 2024-09-19 14:51
Long overdue but this fixes the issue. 

Thank you @simaotwx
